---
debug: false
logs:
  level: DEBUG
  token: ~
mongodb:
  authn: ~
  database: catalog_dev
storagesystems:
  data-sd2e-community:
    posix_path: /work/projects/SD2E-Community/prod/data
only_extant_files: False
downloaded: downloaded.json
pipelines:
  pipeline_uuid: 0ae229a8-45e5-571b-9682-5f1cf83a184c
  updates_nonce: ~
  authn: ~
  pipeline_manager_id: G1p783PxpalBB
  job_manager_id: G56vjoAVzGkkq
  api_server: https://api.sd2e.org
  database: catalog
